/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LangNotFoundImport } from './routes/$lang/not-found'
import { Route as LangMainRouteImport } from './routes/$lang/_main/route'
import { Route as LangAuthRouteImport } from './routes/$lang/_auth/route'
import { Route as LangMainIndexImport } from './routes/$lang/_main/index'
import { Route as LangAuthLoginImport } from './routes/$lang/_auth/login'
import { Route as LangMainJobsRouteImport } from './routes/$lang/_main/jobs/route'
import { Route as LangAuthDashboardRouteImport } from './routes/$lang/_auth/dashboard/route'
import { Route as LangMainJobsIndexImport } from './routes/$lang/_main/jobs/index'
import { Route as LangAuthDashboardIndexImport } from './routes/$lang/_auth/dashboard/index'
import { Route as LangAuthDashboardApplicantsImport } from './routes/$lang/_auth/dashboard/applicants'
import { Route as LangMainJobsSlugRouteImport } from './routes/$lang/_main/jobs/$slug/route'
import { Route as LangMainJobsSlugIndexImport } from './routes/$lang/_main/jobs/$slug/index'
import { Route as LangAuthDashboardJobListImport } from './routes/$lang/_auth/dashboard/job.list'
import { Route as LangAuthDashboardJobCreateImport } from './routes/$lang/_auth/dashboard/job.create'
import { Route as LangMainJobsSlugApplyIndexImport } from './routes/$lang/_main/jobs/$slug/apply.index'
import { Route as LangAuthDashboardJobEditIdImport } from './routes/$lang/_auth/dashboard/job.edit.$id'

// Create Virtual Routes

const LangImport = createFileRoute('/$lang')()

// Create/Update Routes

const LangRoute = LangImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRoute,
} as any)

const LangNotFoundRoute = LangNotFoundImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => LangRoute,
} as any)

const LangMainRouteRoute = LangMainRouteImport.update({
  id: '/_main',
  getParentRoute: () => LangRoute,
} as any)

const LangAuthRouteRoute = LangAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LangRoute,
} as any)

const LangMainIndexRoute = LangMainIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangMainRouteRoute,
} as any)

const LangAuthLoginRoute = LangAuthLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LangAuthRouteRoute,
} as any)

const LangMainJobsRouteRoute = LangMainJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => LangMainRouteRoute,
} as any)

const LangAuthDashboardRouteRoute = LangAuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LangAuthRouteRoute,
} as any)

const LangMainJobsIndexRoute = LangMainJobsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangMainJobsRouteRoute,
} as any)

const LangAuthDashboardIndexRoute = LangAuthDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangAuthDashboardRouteRoute,
} as any)

const LangAuthDashboardApplicantsRoute =
  LangAuthDashboardApplicantsImport.update({
    id: '/applicants',
    path: '/applicants',
    getParentRoute: () => LangAuthDashboardRouteRoute,
  } as any)

const LangMainJobsSlugRouteRoute = LangMainJobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LangMainJobsRouteRoute,
} as any)

const LangMainJobsSlugIndexRoute = LangMainJobsSlugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangMainJobsSlugRouteRoute,
} as any)

const LangAuthDashboardJobListRoute = LangAuthDashboardJobListImport.update({
  id: '/job/list',
  path: '/job/list',
  getParentRoute: () => LangAuthDashboardRouteRoute,
} as any)

const LangAuthDashboardJobCreateRoute = LangAuthDashboardJobCreateImport.update(
  {
    id: '/job/create',
    path: '/job/create',
    getParentRoute: () => LangAuthDashboardRouteRoute,
  } as any,
)

const LangMainJobsSlugApplyIndexRoute = LangMainJobsSlugApplyIndexImport.update(
  {
    id: '/apply/',
    path: '/apply/',
    getParentRoute: () => LangMainJobsSlugRouteRoute,
  } as any,
)

const LangAuthDashboardJobEditIdRoute = LangAuthDashboardJobEditIdImport.update(
  {
    id: '/job/edit/$id',
    path: '/job/edit/$id',
    getParentRoute: () => LangAuthDashboardRouteRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangImport
      parentRoute: typeof rootRoute
    }
    '/$lang/_auth': {
      id: '/$lang/_auth'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangAuthRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/_main': {
      id: '/$lang/_main'
      path: ''
      fullPath: '/$lang'
      preLoaderRoute: typeof LangMainRouteImport
      parentRoute: typeof LangImport
    }
    '/$lang/not-found': {
      id: '/$lang/not-found'
      path: '/not-found'
      fullPath: '/$lang/not-found'
      preLoaderRoute: typeof LangNotFoundImport
      parentRoute: typeof LangImport
    }
    '/$lang/_auth/dashboard': {
      id: '/$lang/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/$lang/dashboard'
      preLoaderRoute: typeof LangAuthDashboardRouteImport
      parentRoute: typeof LangAuthRouteImport
    }
    '/$lang/_main/jobs': {
      id: '/$lang/_main/jobs'
      path: '/jobs'
      fullPath: '/$lang/jobs'
      preLoaderRoute: typeof LangMainJobsRouteImport
      parentRoute: typeof LangMainRouteImport
    }
    '/$lang/_auth/login': {
      id: '/$lang/_auth/login'
      path: '/login'
      fullPath: '/$lang/login'
      preLoaderRoute: typeof LangAuthLoginImport
      parentRoute: typeof LangAuthRouteImport
    }
    '/$lang/_main/': {
      id: '/$lang/_main/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangMainIndexImport
      parentRoute: typeof LangMainRouteImport
    }
    '/$lang/_main/jobs/$slug': {
      id: '/$lang/_main/jobs/$slug'
      path: '/$slug'
      fullPath: '/$lang/jobs/$slug'
      preLoaderRoute: typeof LangMainJobsSlugRouteImport
      parentRoute: typeof LangMainJobsRouteImport
    }
    '/$lang/_auth/dashboard/applicants': {
      id: '/$lang/_auth/dashboard/applicants'
      path: '/applicants'
      fullPath: '/$lang/dashboard/applicants'
      preLoaderRoute: typeof LangAuthDashboardApplicantsImport
      parentRoute: typeof LangAuthDashboardRouteImport
    }
    '/$lang/_auth/dashboard/': {
      id: '/$lang/_auth/dashboard/'
      path: '/'
      fullPath: '/$lang/dashboard/'
      preLoaderRoute: typeof LangAuthDashboardIndexImport
      parentRoute: typeof LangAuthDashboardRouteImport
    }
    '/$lang/_main/jobs/': {
      id: '/$lang/_main/jobs/'
      path: '/'
      fullPath: '/$lang/jobs/'
      preLoaderRoute: typeof LangMainJobsIndexImport
      parentRoute: typeof LangMainJobsRouteImport
    }
    '/$lang/_auth/dashboard/job/create': {
      id: '/$lang/_auth/dashboard/job/create'
      path: '/job/create'
      fullPath: '/$lang/dashboard/job/create'
      preLoaderRoute: typeof LangAuthDashboardJobCreateImport
      parentRoute: typeof LangAuthDashboardRouteImport
    }
    '/$lang/_auth/dashboard/job/list': {
      id: '/$lang/_auth/dashboard/job/list'
      path: '/job/list'
      fullPath: '/$lang/dashboard/job/list'
      preLoaderRoute: typeof LangAuthDashboardJobListImport
      parentRoute: typeof LangAuthDashboardRouteImport
    }
    '/$lang/_main/jobs/$slug/': {
      id: '/$lang/_main/jobs/$slug/'
      path: '/'
      fullPath: '/$lang/jobs/$slug/'
      preLoaderRoute: typeof LangMainJobsSlugIndexImport
      parentRoute: typeof LangMainJobsSlugRouteImport
    }
    '/$lang/_auth/dashboard/job/edit/$id': {
      id: '/$lang/_auth/dashboard/job/edit/$id'
      path: '/job/edit/$id'
      fullPath: '/$lang/dashboard/job/edit/$id'
      preLoaderRoute: typeof LangAuthDashboardJobEditIdImport
      parentRoute: typeof LangAuthDashboardRouteImport
    }
    '/$lang/_main/jobs/$slug/apply/': {
      id: '/$lang/_main/jobs/$slug/apply/'
      path: '/apply'
      fullPath: '/$lang/jobs/$slug/apply'
      preLoaderRoute: typeof LangMainJobsSlugApplyIndexImport
      parentRoute: typeof LangMainJobsSlugRouteImport
    }
  }
}

// Create and export the route tree

interface LangAuthDashboardRouteRouteChildren {
  LangAuthDashboardApplicantsRoute: typeof LangAuthDashboardApplicantsRoute
  LangAuthDashboardIndexRoute: typeof LangAuthDashboardIndexRoute
  LangAuthDashboardJobCreateRoute: typeof LangAuthDashboardJobCreateRoute
  LangAuthDashboardJobListRoute: typeof LangAuthDashboardJobListRoute
  LangAuthDashboardJobEditIdRoute: typeof LangAuthDashboardJobEditIdRoute
}

const LangAuthDashboardRouteRouteChildren: LangAuthDashboardRouteRouteChildren =
  {
    LangAuthDashboardApplicantsRoute: LangAuthDashboardApplicantsRoute,
    LangAuthDashboardIndexRoute: LangAuthDashboardIndexRoute,
    LangAuthDashboardJobCreateRoute: LangAuthDashboardJobCreateRoute,
    LangAuthDashboardJobListRoute: LangAuthDashboardJobListRoute,
    LangAuthDashboardJobEditIdRoute: LangAuthDashboardJobEditIdRoute,
  }

const LangAuthDashboardRouteRouteWithChildren =
  LangAuthDashboardRouteRoute._addFileChildren(
    LangAuthDashboardRouteRouteChildren,
  )

interface LangAuthRouteRouteChildren {
  LangAuthDashboardRouteRoute: typeof LangAuthDashboardRouteRouteWithChildren
  LangAuthLoginRoute: typeof LangAuthLoginRoute
}

const LangAuthRouteRouteChildren: LangAuthRouteRouteChildren = {
  LangAuthDashboardRouteRoute: LangAuthDashboardRouteRouteWithChildren,
  LangAuthLoginRoute: LangAuthLoginRoute,
}

const LangAuthRouteRouteWithChildren = LangAuthRouteRoute._addFileChildren(
  LangAuthRouteRouteChildren,
)

interface LangMainJobsSlugRouteRouteChildren {
  LangMainJobsSlugIndexRoute: typeof LangMainJobsSlugIndexRoute
  LangMainJobsSlugApplyIndexRoute: typeof LangMainJobsSlugApplyIndexRoute
}

const LangMainJobsSlugRouteRouteChildren: LangMainJobsSlugRouteRouteChildren = {
  LangMainJobsSlugIndexRoute: LangMainJobsSlugIndexRoute,
  LangMainJobsSlugApplyIndexRoute: LangMainJobsSlugApplyIndexRoute,
}

const LangMainJobsSlugRouteRouteWithChildren =
  LangMainJobsSlugRouteRoute._addFileChildren(
    LangMainJobsSlugRouteRouteChildren,
  )

interface LangMainJobsRouteRouteChildren {
  LangMainJobsSlugRouteRoute: typeof LangMainJobsSlugRouteRouteWithChildren
  LangMainJobsIndexRoute: typeof LangMainJobsIndexRoute
}

const LangMainJobsRouteRouteChildren: LangMainJobsRouteRouteChildren = {
  LangMainJobsSlugRouteRoute: LangMainJobsSlugRouteRouteWithChildren,
  LangMainJobsIndexRoute: LangMainJobsIndexRoute,
}

const LangMainJobsRouteRouteWithChildren =
  LangMainJobsRouteRoute._addFileChildren(LangMainJobsRouteRouteChildren)

interface LangMainRouteRouteChildren {
  LangMainJobsRouteRoute: typeof LangMainJobsRouteRouteWithChildren
  LangMainIndexRoute: typeof LangMainIndexRoute
}

const LangMainRouteRouteChildren: LangMainRouteRouteChildren = {
  LangMainJobsRouteRoute: LangMainJobsRouteRouteWithChildren,
  LangMainIndexRoute: LangMainIndexRoute,
}

const LangMainRouteRouteWithChildren = LangMainRouteRoute._addFileChildren(
  LangMainRouteRouteChildren,
)

interface LangRouteChildren {
  LangAuthRouteRoute: typeof LangAuthRouteRouteWithChildren
  LangMainRouteRoute: typeof LangMainRouteRouteWithChildren
  LangNotFoundRoute: typeof LangNotFoundRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangAuthRouteRoute: LangAuthRouteRouteWithChildren,
  LangMainRouteRoute: LangMainRouteRouteWithChildren,
  LangNotFoundRoute: LangNotFoundRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

export interface FileRoutesByFullPath {
  '/$lang': typeof LangMainRouteRouteWithChildren
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/dashboard': typeof LangAuthDashboardRouteRouteWithChildren
  '/$lang/jobs': typeof LangMainJobsRouteRouteWithChildren
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/': typeof LangMainIndexRoute
  '/$lang/jobs/$slug': typeof LangMainJobsSlugRouteRouteWithChildren
  '/$lang/dashboard/applicants': typeof LangAuthDashboardApplicantsRoute
  '/$lang/dashboard/': typeof LangAuthDashboardIndexRoute
  '/$lang/jobs/': typeof LangMainJobsIndexRoute
  '/$lang/dashboard/job/create': typeof LangAuthDashboardJobCreateRoute
  '/$lang/dashboard/job/list': typeof LangAuthDashboardJobListRoute
  '/$lang/jobs/$slug/': typeof LangMainJobsSlugIndexRoute
  '/$lang/dashboard/job/edit/$id': typeof LangAuthDashboardJobEditIdRoute
  '/$lang/jobs/$slug/apply': typeof LangMainJobsSlugApplyIndexRoute
}

export interface FileRoutesByTo {
  '/$lang': typeof LangMainIndexRoute
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/login': typeof LangAuthLoginRoute
  '/$lang/dashboard/applicants': typeof LangAuthDashboardApplicantsRoute
  '/$lang/dashboard': typeof LangAuthDashboardIndexRoute
  '/$lang/jobs': typeof LangMainJobsIndexRoute
  '/$lang/dashboard/job/create': typeof LangAuthDashboardJobCreateRoute
  '/$lang/dashboard/job/list': typeof LangAuthDashboardJobListRoute
  '/$lang/jobs/$slug': typeof LangMainJobsSlugIndexRoute
  '/$lang/dashboard/job/edit/$id': typeof LangAuthDashboardJobEditIdRoute
  '/$lang/jobs/$slug/apply': typeof LangMainJobsSlugApplyIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/$lang': typeof LangRouteWithChildren
  '/$lang/_auth': typeof LangAuthRouteRouteWithChildren
  '/$lang/_main': typeof LangMainRouteRouteWithChildren
  '/$lang/not-found': typeof LangNotFoundRoute
  '/$lang/_auth/dashboard': typeof LangAuthDashboardRouteRouteWithChildren
  '/$lang/_main/jobs': typeof LangMainJobsRouteRouteWithChildren
  '/$lang/_auth/login': typeof LangAuthLoginRoute
  '/$lang/_main/': typeof LangMainIndexRoute
  '/$lang/_main/jobs/$slug': typeof LangMainJobsSlugRouteRouteWithChildren
  '/$lang/_auth/dashboard/applicants': typeof LangAuthDashboardApplicantsRoute
  '/$lang/_auth/dashboard/': typeof LangAuthDashboardIndexRoute
  '/$lang/_main/jobs/': typeof LangMainJobsIndexRoute
  '/$lang/_auth/dashboard/job/create': typeof LangAuthDashboardJobCreateRoute
  '/$lang/_auth/dashboard/job/list': typeof LangAuthDashboardJobListRoute
  '/$lang/_main/jobs/$slug/': typeof LangMainJobsSlugIndexRoute
  '/$lang/_auth/dashboard/job/edit/$id': typeof LangAuthDashboardJobEditIdRoute
  '/$lang/_main/jobs/$slug/apply/': typeof LangMainJobsSlugApplyIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$lang'
    | '/$lang/not-found'
    | '/$lang/dashboard'
    | '/$lang/jobs'
    | '/$lang/login'
    | '/$lang/'
    | '/$lang/jobs/$slug'
    | '/$lang/dashboard/applicants'
    | '/$lang/dashboard/'
    | '/$lang/jobs/'
    | '/$lang/dashboard/job/create'
    | '/$lang/dashboard/job/list'
    | '/$lang/jobs/$slug/'
    | '/$lang/dashboard/job/edit/$id'
    | '/$lang/jobs/$slug/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$lang'
    | '/$lang/not-found'
    | '/$lang/login'
    | '/$lang/dashboard/applicants'
    | '/$lang/dashboard'
    | '/$lang/jobs'
    | '/$lang/dashboard/job/create'
    | '/$lang/dashboard/job/list'
    | '/$lang/jobs/$slug'
    | '/$lang/dashboard/job/edit/$id'
    | '/$lang/jobs/$slug/apply'
  id:
    | '__root__'
    | '/$lang'
    | '/$lang/_auth'
    | '/$lang/_main'
    | '/$lang/not-found'
    | '/$lang/_auth/dashboard'
    | '/$lang/_main/jobs'
    | '/$lang/_auth/login'
    | '/$lang/_main/'
    | '/$lang/_main/jobs/$slug'
    | '/$lang/_auth/dashboard/applicants'
    | '/$lang/_auth/dashboard/'
    | '/$lang/_main/jobs/'
    | '/$lang/_auth/dashboard/job/create'
    | '/$lang/_auth/dashboard/job/list'
    | '/$lang/_main/jobs/$slug/'
    | '/$lang/_auth/dashboard/job/edit/$id'
    | '/$lang/_main/jobs/$slug/apply/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LangRoute: typeof LangRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LangRoute: LangRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/$lang"
      ]
    },
    "/$lang": {
      "filePath": "$lang/_auth",
      "children": [
        "/$lang/_auth",
        "/$lang/_main",
        "/$lang/not-found"
      ]
    },
    "/$lang/_auth": {
      "filePath": "$lang/_auth/route.tsx",
      "parent": "/$lang",
      "children": [
        "/$lang/_auth/dashboard",
        "/$lang/_auth/login"
      ]
    },
    "/$lang/_main": {
      "filePath": "$lang/_main/route.tsx",
      "parent": "/$lang",
      "children": [
        "/$lang/_main/jobs",
        "/$lang/_main/"
      ]
    },
    "/$lang/not-found": {
      "filePath": "$lang/not-found.tsx",
      "parent": "/$lang"
    },
    "/$lang/_auth/dashboard": {
      "filePath": "$lang/_auth/dashboard/route.tsx",
      "parent": "/$lang/_auth",
      "children": [
        "/$lang/_auth/dashboard/applicants",
        "/$lang/_auth/dashboard/",
        "/$lang/_auth/dashboard/job/create",
        "/$lang/_auth/dashboard/job/list",
        "/$lang/_auth/dashboard/job/edit/$id"
      ]
    },
    "/$lang/_main/jobs": {
      "filePath": "$lang/_main/jobs/route.tsx",
      "parent": "/$lang/_main",
      "children": [
        "/$lang/_main/jobs/$slug",
        "/$lang/_main/jobs/"
      ]
    },
    "/$lang/_auth/login": {
      "filePath": "$lang/_auth/login.tsx",
      "parent": "/$lang/_auth"
    },
    "/$lang/_main/": {
      "filePath": "$lang/_main/index.tsx",
      "parent": "/$lang/_main"
    },
    "/$lang/_main/jobs/$slug": {
      "filePath": "$lang/_main/jobs/$slug/route.tsx",
      "parent": "/$lang/_main/jobs",
      "children": [
        "/$lang/_main/jobs/$slug/",
        "/$lang/_main/jobs/$slug/apply/"
      ]
    },
    "/$lang/_auth/dashboard/applicants": {
      "filePath": "$lang/_auth/dashboard/applicants.tsx",
      "parent": "/$lang/_auth/dashboard"
    },
    "/$lang/_auth/dashboard/": {
      "filePath": "$lang/_auth/dashboard/index.tsx",
      "parent": "/$lang/_auth/dashboard"
    },
    "/$lang/_main/jobs/": {
      "filePath": "$lang/_main/jobs/index.tsx",
      "parent": "/$lang/_main/jobs"
    },
    "/$lang/_auth/dashboard/job/create": {
      "filePath": "$lang/_auth/dashboard/job.create.tsx",
      "parent": "/$lang/_auth/dashboard"
    },
    "/$lang/_auth/dashboard/job/list": {
      "filePath": "$lang/_auth/dashboard/job.list.tsx",
      "parent": "/$lang/_auth/dashboard"
    },
    "/$lang/_main/jobs/$slug/": {
      "filePath": "$lang/_main/jobs/$slug/index.tsx",
      "parent": "/$lang/_main/jobs/$slug"
    },
    "/$lang/_auth/dashboard/job/edit/$id": {
      "filePath": "$lang/_auth/dashboard/job.edit.$id.tsx",
      "parent": "/$lang/_auth/dashboard"
    },
    "/$lang/_main/jobs/$slug/apply/": {
      "filePath": "$lang/_main/jobs/$slug/apply.index.tsx",
      "parent": "/$lang/_main/jobs/$slug"
    }
  }
}
ROUTE_MANIFEST_END */
